name: core_ui
description: AE Core UI Lib
version: 0.2.1+201
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core

  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/themes/dark/
    - assets/themes/light/